### ISSUE TITLE
manifest.json doesn't provide a valid id

### ISSUE THREAD

**Issue by saildata** [Enchufadoo/fixedzoom#11]
Nothing major.. just something I noticed...

The manifest.json file doesn't provide a valid id under gecko. See the [MDN example file](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json#Example).

You can tell that the id is missing when looking at **about:telemetry#environment-data-tab** in Firefox.

![image](https://user-images.githubusercontent.com/11636184/46640594-85fa4000-cb5c-11e8-8f09-8a05ae56dc92.png)

Here is an example of uBlock on the same page, with the valid id:

![image](https://user-images.githubusercontent.com/11636184/46640622-acb87680-cb5c-11e8-9511-b053a5a5739e.png)

**Comment by Enchufadoo** [comment]
Yeah I know, I uploaded the extension without one and when I tried to fix it by modifying the ID addons.mozilla sort of created a new version of the extension and the updates I was doing didn't appear if you had the extension installed with the old ID (or that's what I seemed to notice since I had the extension in a couple of computers).
