### ISSUE TITLE
zooming in on images

### ISSUE THREAD

**Issue by iwconfig** [Enchufadoo/fixedzoom#20]
Oops, sorry. Clumsy fingers here trying to type in bed in the dark. Creating empty issues with weird titles is not something I usually do :grinning: 

OnT: I have set a default zoom level to 120%, and when i try to zoom in on images the zoom level resets back to 120% as soon as the image reaches the browsers content border. Check this out:

![recorded](https://user-images.githubusercontent.com/10843441/52753331-7ac98c00-2ff6-11e9-8c6c-ffdcbb4c8eaa.gif)

Is this a bug or a "limitation" in Firefox API?

**Comment by Enchufadoo** [comment]
I wish I could blame the API ha, I didn't try to fix it because I don't want to break something else in the process. 

Check the modifications I made (2.1.2) I tried to trigger it with the github avatars and at least in my browser its fixed.

If it's still bugged, give a link to the image you are testing it with.

**Comment by iwconfig** [comment]
Yes, it's fixed! Works perfectly. Thank you! :)
