### ISSUE TITLE
Actually use variable complete

### ISSUE THREAD

**Issue by SpineEyE** [Enchufadoo/fixedzoom#4]
Looked into your code and I think there's a mistake in line 44 (background.js) where you check for enabled. I think you wanted to check for `complete`.

**Comment by Enchufadoo** [comment]
Nope, the problem is this:

If you only change the zoom on complete then the tab will open in 100% stay a couple of seconds with that zoom and only when all assets are downloaded the complete status changes.

So it´s awful! it´s like all the time the browser is toggling the zoom when you change the url. I know that if I do this the event it´s called like 5 times but I can't figure out another way to make the zoom seem seamless.

I tried for example to do the zoom change only in the beginning of onUpdated and on "complete" status but it´s of no use either, firefox sometimes changes the zoom back on like the fourth event between urls or who knows. 

Maybe there's a way to do this with the onZoomChange but I haven't tried it yet.

**Comment by SpineEyE** [comment]
Although I'm interested in contributing to this addon, I don't have time to look into these bugs for the next month or so. So feel free but instead of publishing a new version fast, test thoroughly, please :)

**Comment by Enchufadoo** [comment]
Look at it whenever you can, thanks.

**Comment by SpineEyE** [comment]
Will do. Just another idea that came to my mind and could ideally be implemented: Give the user a choice between light resource usage and fast response times. If the latter option is chosen, use the current approach to trigger on every event and if the user wants light resource usage, only trigger if the complete flag is given. Or was there a problem with that before? Because for me this seemed to be working perfectly fine.

**Comment by Enchufadoo** [comment]
> Or was there a problem with that before?

with only changing the zoom on complete status?

**Comment by SpineEyE** [comment]
Yes

**Comment by Enchufadoo** [comment]
> If you only change the zoom on complete then the tab will open in 100% stay a couple of seconds with that zoom and only when all assets are downloaded the complete status changes.
> 
> So it´s awful! it´s like all the time the browser is toggling the zoom when you change the url. I know that if I do this the event it´s called like 5 times but I can't figure out another way to make the zoom seem seamless.

**Comment by SpineEyE** [comment]
Well, you only have this lag once per domain and in my case it wasn't really noticeable. That's why I thought about the option for fast response times vs. light resource usage, i.e. fewer times that the addon cycles through each tab and changes their zoom level.

**Comment by Enchufadoo** [comment]
On new window too, when opening the browser, on new tab and on domain change, I think.

**Comment by SpineEyE** [comment]
I see you improved the code for performance and this issue is not valid anymore.
